FROM haproxy:latest

#RUN mkdir -p /run/haproxy

COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
#ENTRYPOINT ["/bin/sh", "-c", "mkdir -p /run/haproxy && exec haproxy -f /usr/local/etc/haproxy/haproxy.cfg"]
