input {
  beats {
    port => 5044
#    codec => json
  }
}

filter {
  # You can add grok, date parsing, etc. here if needed
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "dev-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
