input {
  tcp {
    port => 5000
    codec => json
#    ssl => false
  }
}

filter {
  # You can add grok, date parsing, etc. here if needed
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "dev-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
